const jobCards = [
  {
    id: 1,
    company: "Amazon",
    logo: "https://www.pngall.com/wp-content/uploads/15/Amazon-Smile-A-Logo.png",
    postedAgo: "5 days ago",
    title: "Senior UI/UX Designer",
    tags: ["Part-Time", "Senior Level"],
    salary: "$120/hr",
    location: "Mumbai, India",
  },
  {
    id: 2,
    company: "Google",
    logo: "https://thumbs.dreamstime.com/b/google-logo-vector-format-white-background-illustration-407571048.jpg",
    postedAgo: "30 days ago",
    title: "Graphic Designer",
    tags: ["Part-Time", "Flexible Schedule"],
    salary: "$150-220k",
    location: "Kochi, India",
  },
  {
    id: 3,
    company: "Dribble",
    logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ-zdLpQ1XogOHnpR9MuW1MD9oXYxuPS5FCgQ&s",
    postedAgo: "18 days ago",
    title: "Senior Motion Designer",
    tags: ["Contract", "Remote"],
    salary: "$85/hr",
    location: "Chennai, India",
  },
  {
    id: 4,
    company: "Figma",
    logo: "https://growth-hero.com/wp-content/uploads/2024/08/sticker-png-user-interface-design-figma-computer-software-user-experience-design-web-design-user-interface-design-logo-usability-user-interface-thumbnail.png",
    postedAgo: "5 days ago",
    title: "UX Designer",
    tags: ["Full-Time", "In office"],
    salary: "$200-250k",
    location: "Bangalore, India",
  },
  {
    id: 5,
    company: "Airbnb",
    logo: "https://static.vecteezy.com/system/resources/previews/074/690/615/non_2x/airbnb-red-logo-circular-symbol-mark-illustration-free-png.png",
    postedAgo: "5 days ago",
    title: "Junior UI/UX Designer",
    tags: ["Contract", "Remote"],
    salary: "$100/hr",
    location: "Delhi, India",
  },
  {
    id: 6,
    company: "Apple",
    logo: "https://i.pinimg.com/736x/1e/c1/1a/1ec11a869384bc5e59625bac39b6a099.jpg",
    postedAgo: "5 days ago",
    title: "Graphic Designer",
    tags: ["Full-Time", "Flexible Schedule"],
    salary: "$85-120k",
    location: "Kerala, India",
  },
  {
    id: 7,
    company: "Netflix",
    logo: "https://upload.wikimedia.org/wikipedia/commons/0/08/Netflix_2015_logo.svg",
    postedAgo: "2 days ago",
    title: "Product Designer",
    tags: ["Full-Time", "Remote"],
    salary: "$180-240k",
    location: "Hyderabad, India",
  },
  {
    id: 8,
    company: "Spotify",
    logo: "https://upload.wikimedia.org/wikipedia/commons/1/19/Spotify_logo_without_text.svg",
    postedAgo: "12 days ago",
    title: "UI Designer",
    tags: ["Part-Time", "Remote"],
    salary: "$90/hr",
    location: "Pune, India",
  },
  {
    id: 9,
    company: "Adobe",
    logo: "https://static.vecteezy.com/system/resources/previews/073/495/096/non_2x/adobe-inc-logo-circular-glossy-icon-with-transparent-background-free-png.png",
    postedAgo: "7 days ago",
    title: "Senior Product Designer",
    tags: ["Full-Time", "In office"],
    salary: "$220-280k",
    location: "Mumbai, India",
  },
  {
    id: 10,
    company: "Meta",
    logo: "https://images.rawpixel.com/image_png_social_square/czNmcy1wcml2YXRlL3Jhd3BpeGVsX2ltYWdlcy93ZWJzaXRlX2NvbnRlbnQvbHIvdjEwOTEtMDNfMS5wbmc.png",
    postedAgo: "1 day ago",
    title: "Frontend Developer",
    tags: ["Full-Time", "Remote"],
    salary: "$140/hr",
    location: "Bangalore, India",
  },
];

export default jobCards;